apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-front
  template:
    metadata:
      labels:
        app: web-front
    spec:
      containers:
        - name: web-front
          image: registry.cn-beijing.aliyuncs.com/damondocker/web-front:{version}
          ports:
            - name: http-port
              containerPort: 8080
          env:
            - name: spring_profiles_active
              value: k8s
      imagePullSecrets:
        - name: sba
